FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y make gcc

COPY . /tinycc
WORKDIR /tinycc
RUN ./configure --prefix=/install
RUN make
RUN make install

FROM ubuntu:20.04 as package
COPY --from=builder /install /install
